#!/bin/bash

# Copyright 2015 Jonathan Vasquez <jvasquez1011@gmail.com>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

_snapshots+=($(zfs list -t snapshot -o name -s name -H | grep _))
_snapshots_count="${#_snapshots[@]}"

if [[ ${_snapshots_count} -eq 0 ]]; then
	echo "There are no snapshots to rename."
	exit
fi

echo "Amount of snapshots to rename: ${_snapshots_count}"
echo "Example: tank/gentoo/root@05_10_15_0350 -> tank/gentoo/root@2015-05-10-0350-01"
echo -n "Proceed [y/N]: " && read _choice

case "${_choice}" in
y|Y) ;;
n|N)
	echo "Not doing anything. Exiting"
	exit 0
	;;
*)
	echo "Invalid or no option given. Exiting."
	exit 1
	;;
esac

for i in ${!_snapshots[@]}; do
	_dataset="${_snapshots[i]}"
	_display_count=`expr ${i} + 1`

	_dataset_name=$(echo ${_dataset} | cut -d "@" -f 1)
	_dataset_date=$(echo ${_dataset} | cut -d "@" -f 2)

	_date_year=$(echo ${_dataset_date} | cut -d "_" -f 3)
	_date_month=$(echo ${_dataset_date} | cut -d "_" -f 1)
	_date_day=$(echo ${_dataset_date} | cut -d "_" -f 2)
	_date_time=$(echo ${_dataset_date} | cut -d "_" -f 4)

	_date_new_year="20${_date_year}"
	_date_seconds="01"

	_dataset_new_date="${_date_new_year}-${_date_month}-${_date_day}-${_date_time}-${_date_seconds}"
	_dataset_new="${_dataset_name}@${_dataset_new_date}"

	echo "${_display_count}: ${_dataset} -> ${_dataset_new}"
	zfs rename ${_dataset} ${_dataset_new}
done

echo "Amount of snapshots renamed: ${_snapshots_count}"
