#!/bin/bash

# Copyright 2013-2015 Jonathan Vasquez <jvasquez1011@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, see <http://www.gnu.org/licenses/>.

# Address
EMAIL="root@localhost"

MAIL="/usr/bin/mailx"
ZPOOL="/sbin/zpool"

GOOD="all pools are healthy"
RESULT="$(${ZPOOL} status -x)"

if [[ ${RESULT} != ${GOOD} ]]; then
    echo -e "[ALERT] Your pool is DEGRADED.\n\nOutput:\n\n$(${ZPOOL} status)" |
    ${MAIL} -s "[ZFS] Status: DEGRADED" ${EMAIL}
fi
