#!/bin/bash

# Copyright 2013-2015 Jonathan Vasquez <jvasquez1011@gmail.com>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Address
EMAIL="root@localhost"

MAIL="/usr/bin/mailx"
ZPOOL="/sbin/zpool"

GOOD="all pools are healthy"
RESULT="$(${ZPOOL} status -x)"

if [[ ${RESULT} != ${GOOD} ]]; then
    echo -e "[ALERT] Your pool is DEGRADED.\n\nOutput:\n\n$(${ZPOOL} status)" |
    ${MAIL} -s "[ZFS] Status: DEGRADED" ${EMAIL}
fi
