#!/bin/bash

# Copyright 2013-2015 Jonathan Vasquez <jvasquez1011@gmail.com>
# Licensed under the Simplified BSD License which can be found in the LICENSE file.

# Address
EMAIL="root@localhost"

MAIL="/usr/bin/mailx"
ZPOOL="/sbin/zpool"

GOOD="all pools are healthy"
RESULT="$(${ZPOOL} status -x)"

if [[ ${RESULT} != ${GOOD} ]]; then
    echo -e "[ALERT] Your pool is DEGRADED.\n\nOutput:\n\n$(${ZPOOL} status)" |
    ${MAIL} -s "[ZFS] Status: DEGRADED" ${EMAIL}
fi
