#!/bin/bash

# Copyright 2013-2015 Jonathan Vasquez <jvasquez1011@gmail.com>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

SPATH="/usr/local/sbin"

if [[ $# -lt 1 ]]; then
    echo "Please pass a tag for your snapshots."
    exit 1
fi

_TAG=$1

# Takes a controlled snapshot of each dataset in the 'tank' pool
${SPATH}/zfs_snapshot ${_TAG} \
    tank/gentoo/root \
    tank/gentoo/home
