#!/bin/bash

# Copyright 2013-2015 Jonathan Vasquez <jvasquez1011@gmail.com>
# Licensed under the Simplified BSD License which can be found in the LICENSE file.

SPATH="/usr/local/sbin"

# Takes a controlled snapshot of each dataset in the 'tank' pool
${SPATH}/zfs_snapshot \
    tank/gentoo/root \
    tank/gentoo/home
