#!/bin/bash

# Copyright 2013-2015 Jonathan Vasquez <jvasquez1011@gmail.com>
# Licensed under the Simplified BSD License which can be found in the LICENSE file.

SPATH="/usr/local/sbin"

# Backup the following datasets into the 'backup' pool
${SPATH}/zfs_backup backup \
    tank/gentoo/root \
    tank/gentoo/home
