#!/bin/bash

SPATH="/usr/local/sbin"

# Backup the following datasets into the 'backup' pool
${SPATH}/zfs_backup backup \
	tank/gentoo/root \
	tank/gentoo/home \
	tank/gentoo/src \
	tank/gentoo/portage
