#!/bin/bash

# Copyright 2014 Jonathan Vasquez <jvasquez1011@gmail.com>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

SPATH="/usr/local/sbin"

# Backup the following datasets into the 'backup' pool
${SPATH}/zfs_backup backup \
	tank/gentoo/root \
	tank/gentoo/home \
	tank/gentoo/src \
	tank/gentoo/portage
