#!/bin/bash

# Copyright 2013-2015 Jonathan Vasquez <jvasquez1011@gmail.com>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

ZFS="/sbin/zfs"

if [[ $# -eq 0 ]]; then
    echo "You haven't passed a pool name. Exiting."
    exit
fi

while [ "$1" ]; do
    ${ZFS} snapshot $1@$(date +%m_%d_%y_%H%M)
    shift
done
