#!/bin/bash

# Copyright 2013-2015 Jonathan Vasquez <jvasquez1011@gmail.com>
# Licensed under the Simplified BSD License which can be found in the LICENSE file.

ZFS="/sbin/zfs"

if [[ $# -eq 0 ]]; then
    echo "You haven't passed a pool name. Exiting."
    exit
fi

while [ "$1" ]; do
    ${ZFS} snapshot $1@$(date +%m_%d_%y_%H%M)
    shift
done
