#!/bin/bash

# Copyright 2013-2015 Jonathan Vasquez <jvasquez1011@gmail.com>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

ZFS="/sbin/zfs"

if [[ $# -eq 0 ]]; then
    echo "You haven't passed a pool name. Exiting."
    exit
fi

# Get the date so that we can have a stable "seconds" count.
# This will prevent the seconds from being off by a few in between
# different snapshots.
_DATE=$(date +%F-%H%M-%S)

while [ "$1" ]; do
    ${ZFS} snapshot $1@${_DATE}
    shift
done
