#!/bin/bash

# Copyright 2013-2014 Jonathan Vasquez <jvasquez1011@gmail.com>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# The parameter passed to this script will be the name of the pool that you want to scrub

# Example: # zpool_scrub tank

ZPOOL="/sbin/zpool"

if [[ -z ${1} ]]; then
	echo "You haven't passed a pool name. Exiting."
	exit
fi

${ZPOOL} scrub ${1} 
