#!/bin/bash

# Copyright 2013-2015 Jonathan Vasquez <jvasquez1011@gmail.com>
# Licensed under the Simplified BSD License which can be found in the LICENSE file.

# The parameter passed to this script will be the name of the pool that you want to scrub

# Example: # zpool_scrub tank

ZPOOL="/sbin/zpool"

if [[ -z ${1} ]]; then
    echo "You haven't passed a pool name. Exiting."
    exit
fi

${ZPOOL} scrub ${1}
