#!/bin/bash

# Copyright (C) 2013-2019 Jonathan Vasquez <jon@xyinn.org>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Description: Takes a btrfs snapshot starting from a top-level dataset and organizes the snapshots by date

# params : btrfs_snapshot <path to root of btrfs volume dataset>
# example: btrfs_snapshot /mnt/toplevel/tank

if [[ -z $1 ]]; then
    echo "Please pass in the location of the top-level dataset/subvolume."
    exit 1
fi

BTRFS="/sbin/btrfs"
BTRFS_OPTS="-r"

# strip last / char if exists (otherwise would cause pool_name to be null if user passes a directory with a final /)
STRIPPED="${1%/}"
POOL_NAME="${STRIPPED##*/}"
TOP_LEVEL="${1%/*}"

SNAPSHOT_DATE=$(date +%F-%H%M-%S)
SNAPSHOTS_DIR_NAME="snapshots"

POOL_TOP_LEVEL="${TOP_LEVEL}/${POOL_NAME}"

if [[ ! -d ${POOL_TOP_LEVEL} ]]; then
    echo "Unable to find: ${POOL_TOP_LEVEL}"
    exit 1
fi

for target in $(ls ${POOL_TOP_LEVEL}); do
    if [[ ${target} == "snapshots" ]]; then
        break
    fi

    SOURCE_PATH="${POOL_TOP_LEVEL}/${target}"
    TARGET_PATH="${POOL_TOP_LEVEL}/${SNAPSHOTS_DIR_NAME}/${SNAPSHOT_DATE}/${target}"
    SNAPSHOT_DIR="$(dirname ${TARGET_PATH})"

    if [[ ! -d ${SNAPSHOT_DIR} ]]; then
        mkdir -p "${SNAPSHOT_DIR}"

        if [[ ! -d ${SNAPSHOT_DIR} ]]; then
            echo "Unable to create the snapshot directory: ${SNAPSHOT_DIR}"
            exit 1
        fi
    fi

    ${BTRFS} subvolume snapshot ${BTRFS_OPTS} ${SOURCE_PATH} ${TARGET_PATH}
done
