#!/bin/sh

# Copyright (C) 2013-2020 Jonathan Vasquez <jon@xyinn.org>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

EMAIL="root@localhost"

MAIL="/usr/bin/mail"
ZPOOL="/sbin/zpool"

GOOD="all pools are healthy"
RESULT="$(${ZPOOL} status -x)"

if [ "${RESULT}" != "${GOOD}" ]; then
    echo -e "[ALERT] Your pool is DEGRADED.\n\nOutput:\n\n$(${ZPOOL} status)" |
    ${MAIL} -s "[ZFS] Status: DEGRADED" ${EMAIL}
fi
