#!/bin/sh

# Copyright (C) 2013-2020 Jonathan Vasquez <jon@xyinn.org>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ -z "$1" ]; then
	echo "No pool name passed in!"
	exit 1
fi

pool="$1"
exclude_file="/root/excluded_snapshots"
honeydew -p "${pool}" -e "${exclude_file}" -x -d 2099-01-01-0000-00 -i 500
