#!/bin/bash

# Copyright (C) 2013-2019 Jonathan Vasquez <jon@xyinn.org>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Dependencies:
# - tar
# - pxz

_DATE="$(date +%F-%H%M-%S)"
backup="backup-${_DATE}.tar"
backup_compressed="${backup}.xz"
backup_dir="/tank/system/"

# Switch to root of system
cd /

echo "Backing up system on ${_DATE} ..."

time tar -cvpf "${backup}" \
	--exclude="/${backup}" \
	--exclude=/backup \
	--exclude=/proc \
	--exclude=/dev \
	--exclude=/sys \
	--exclude=/mnt \
	--exclude=/media \
	--exclude=/tmp \
	--exclude=/run \
	--exclude=/var/cache/apt/archives \
	--exclude=/home \
	--exclude=/tank \
	/

echo "Compressing ${backup} ..."
time pxz -v "${backup}"

# Move copy over to ZFS backup dataset
mv "${backup_compressed}" "${backup_dir}"

echo "Complete!"
