#!/bin/bash

# Copyright 2013-2016 Jonathan Vasquez <jvasquez1011@gmail.com>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

SPATH="/usr/local/sbin"
LABEL="$1"

_BACKUP_POOL="backup"

_DATASETS=(
    "boot/gentoo"
    "tank/gentoo/root"
    "tank/gentoo/home"
)

if [[ -z "${LABEL}" ]]; then
    echo "You must pass a label in order to start a backup."
    exit
fi

# Backup the following datasets into the 'backup' pool
for i in "${_DATASETS[@]}"; do
    "${SPATH}"/zfs_backup -f -b "${_BACKUP_POOL}" -d "${i}" -l "${LABEL}"
done
