#!/bin/bash

# Copyright 2013-2016 Jonathan Vasquez <jvasquez1011@gmail.com>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

SPATH="/usr/local/sbin"
LABEL="$1"

# Backup the following datasets into the 'backup' pool
if [[ ! -z "${LABEL}" ]]; then
    "${SPATH}"/zfs_backup -b backup -d boot/gentoo -l "${LABEL}"
    "${SPATH}"/zfs_backup -b backup -d tank/gentoo/root -l "${LABEL}"
    "${SPATH}"/zfs_backup -b backup -d tank/gentoo/home -l "${LABEL}"
else
    "${SPATH}"/zfs_backup -b backup -d boot/gentoo
    "${SPATH}"/zfs_backup -b backup -d tank/gentoo/root
    "${SPATH}"/zfs_backup -b backup -d tank/gentoo/home
fi
