#!/bin/bash

# Copyright (C) 2013-2018 Jonathan Vasquez <jon@xyinn.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see<https://www.gnu.org/licenses/>.

SPATH="/usr/local/sbin"

if [[ $# -lt 1 ]]; then
    echo "Please pass a tag for your snapshots."
    exit 1
fi

_TAG=$1

# Takes a controlled snapshot of each dataset in the 'tank' pool
"${SPATH}"/zfs_snapshot "${_TAG}" \
    tank/home \
    tank/system
