#!/bin/bash

# Copyright 2013-2017 Jonathan Vasquez <jon@xyinn.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

ZFS="/sbin/zfs"

if [[ $# -le 1 ]]; then
    echo "You must pass the time tag and the dataset you want to snapshot."
    echo "Example: zfs_snapshot HOURLY tank/gentoo/root"
    exit
fi

# Get the date so that we can have a stable "seconds" count.
# This will prevent the seconds from being off by a few in between
# different snapshots.
_DATE="$(date +%F-%H%M-%S)"

# A tag for our snapshots. We can use these tags to quickly label things as
# HOURLY, DAILY, MONTHLY, YEARLY. Technically this tag can be anything you want.
_TAG=$1
_FULL_SNAPSHOT_NAME="${_DATE}-${_TAG}"

# Skip the first parameter since this is just the tag which is stable
# across all of our dataset snapshot names.
shift

while [ "$1" ]; do
    "${ZFS}" snapshot $1@"${_FULL_SNAPSHOT_NAME}"
    shift
done
