#!/bin/bash

# Copyright (C) 2013-2019 Jonathan Vasquez <jon@xyinn.org>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ZFS="/sbin/zfs"

if [[ $# -le 1 ]]; then
    echo "You must pass the time tag and the dataset you want to snapshot."
    echo "Example: zfs_snapshot HOURLY tank/gentoo/root"
    exit
fi

# Get the date so that we can have a stable "seconds" count.
# This will prevent the seconds from being off by a few in between
# different snapshots.
_DATE="$(date +%F-%H%M-%S)"

# A tag for our snapshots. We can use these tags to quickly label things as
# HOURLY, DAILY, MONTHLY, YEARLY. Technically this tag can be anything you want.
_TAG=$1
_FULL_SNAPSHOT_NAME="${_DATE}-${_TAG}"

# Skip the first parameter since this is just the tag which is stable
# across all of our dataset snapshot names.
shift

while [ "$1" ]; do
    "${ZFS}" snapshot $1@"${_FULL_SNAPSHOT_NAME}"
    shift
done
